
kind: pipeline
type: kubernetes
name: default

steps:
- name: dev-build
  pull: if-not-exists
  image: python:3.7
  commands:
  - echo ${DRONE_BRANCH} - ${DRONE_BUILD_EVENT}
  - docker build -f Dockerfile.test -t ut .
  # - python --version
  # - pip install -r requirements.txt
  # - python upload.py
#   - python -m compileall ./src
  dockerfile: Dockerfile
  when:
    event:
    - push