
kind: pipeline
type: kubernetes
name: default

steps:
- name: dev-build
  pull: if-not-exists
  image: ihealthlabs/test_image_sage:0.2
  commands:
  - echo ${DRONE_BRANCH} - ${DRONE_BUILD_EVENT}
 
  - python upload.py
#   - python -m compileall ./src
  dockerfile: Dockerfile
  when:
    event:
    - push
    
- name: coverage
  image: ihealthlabs/coverage_webhook:0.1