
kind: pipeline
type: kubernetes
name: default

steps:
- name: dev-build
  pull: if-not-exists
  image: python:3.7
  commands:
  - echo ${DRONE_BRANCH}${DRONE_BUILD_EVENT}
  - python --version
  - python upload.py
#   - python -m compileall ./src
  when:
    event:
    - push